name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Deloyment task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Retrieve node and npm
        uses: actions/setup-node@v2
        with:
          node-version: 'v12.16.3'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npm publish